### PR TITLE
pa: updating to a cleaner way on how we check for vault token capabilities

### PR DESCRIPTION
**Pull request by saipranav**
using sys/capabilities-self for finding if a token has required capabilities.
https://pkg.go.dev/github.com/hashicorp/vault/api#Sys.CapabilitiesSelf
https://www.vaultproject.io/api/system/capabilities-self

Changed a little bit with bit checks (pun haha)

### CODE REVIEW

**Comment by saipranav** [comment]
Linked with #28

**Comment by saipranav** [comment]
@cyrinux and @maximbaz Can you review this when you find some free time? Thanks for your contributions.

**Comment by saipranav** [comment]
Tests passed locally with local bootstrap script

**Comment by cyrinux** [comment]
Hi @saipranav , this LGTM, well done, its simpler and nicer ! Congrats 👍🏻 !

**Review by cyrinux — APPROVED** [review]

**Comment by maximbaz** [comment]
Looks good to me too, and the bitwise logic seems correct now 👍

**Comment by saipranav** [comment]
Thanks, @cyrinux for the contribution. 
I am doing good, safe and healthy. Hope you and your family are too.

Thanks, @maximbaz for your contribution.
Hope you and your family are well.

**Pull request merged**
