### PR TITLE
Fix checks permissions, fix #27

### LINKED ISSUE #27: Entries disappear randomly on the destination
Hi @saipranav ! 
I progress on my project and I realize time to time, maybe during a sync pass, I got some entries that disappears.
Something like the sync process on each pass, even if no modifications on the kv, first delete the entries, sleep, then write the new/same value.
To quickly say, i feel my entries "blink" in the kv store.
Any idea? This is not atomic?
Thanks you!

ps: I use the last version

### PR DESCRIPTION
**Pull request by cyrinux**
This will do only the necessary checks, this allow to got an "hardened" policy with only giving write permissions in the vsyncChecks path.

This fix all my sync issues with #29 

With this policy for the origin (we can maybe remove more perms)

```
$ vault policy read vsync-ro
path "auth/token/lookup-self" {
  capabilities = ["read"]
}
path "kv/*" {
    capabilities = ["list", "read"]
}
path "kv/data/*" {
  capabilities = ["list", "read"]
}
path "kv/metadata/*" {
  capabilities = ["list", "read"]
}
path "kv/metadata/vsyncChecks" {
  capabilities = ["create", "read", "update", "delete", "list"]
}
path "kv/data/vsyncChecks" {
  capabilities = ["create", "read", "update", "list"]
}
path "kv/metadata/vsyncChecks/*" {
  capabilities = ["create", "read", "update", "delete", "list"]
}
path "kv/data/vsyncChecks/*" {
  capabilities = ["create", "read", "update", "delete", "list"]
}
path "sys/mounts" {
  capabilities = ["list", "read"]
}
path "sys/mounts/*" {
  capabilities = ["list", "read"]
}
path "sys/policies/*" {
    capabilities = ["list", "read"]
}
path "sys/policy/*" {
    capabilities = ["list", "read"]
}
path "sys/policy" {
    capabilities = ["list", "read"]
}
path "auth/approle/*" {
    capabilities = ["list"]
}
path "auth/approle/vsync-ro" {
    capabilities = ["read"]
}
````

Does it make sense for you?

kudos to @maximbaz who help me on this.

### CODE REVIEW

**Comment by saipranav** [comment]
Hi @cyrinux,

Sorry for the delay.

Great to hear your vsync jobs are healthy too.

I finally migrated all of my vsync jobs to use approle with pretty good policies. It's been running well for almost a month. 
I will be monitoring my vsync jobs in case there is any issue related to our conversation I am more than happy to reopen the PRs. I am also unable to replicate the error messages with a similar origin policy.
Feel free to reopen if needed.

Totally grateful for your contributions on approle we love it. Thanks Maximbaz.

Thanks again,
Sai Pranav

**Comment by maximbaz** [comment]
hey @saipranav, this PR simply fixes a binary logic, just experiment with this diff on simple examples and you will see why it's wrong. 

for example 

```
checks = 2
WriteCheck = 2

checks & WriteCheck != 0

checks & (WriteCheck|Anything) != 0
```

`Anything` can really be any value, so simply logically all your blocks of code are useless, they check nothing in this case. 

And so this PR fixes the binary logic. 

Hope that helps, good luck 😉

**Comment by saipranav** [comment]
Hi @maximbaz,

Thanks for the inputs, and thanks for contributing.

Here is my explaination https://play.golang.org/p/aLZo3DzbIuk. For future, In case the play go link failes I have attached go code to this commit for references.

Crux of explaination: 
1. We need to check if user variable is within the valid iotas
2. The checks are done sequentially and we need multiple of if conditions to be valid at each run not just 1 condition

Let me know if I am misunderstanding it. I am open to learn more.
Thanks
[aLZo3DzbIuk.txt](https://github.com/ExpediaGroup/vsync/files/6835549/aLZo3DzbIuk.txt)

**Comment by maximbaz** [comment]
Thanks for making the example 🙂 I think your logic is correct for the boundaries checks, lets now focus on "intersection" checks.

For example, let's take your `CheckTokenPermissions` function. What would be the value of `checks` argument that I need to pass, such that the code will enter the first `if` (`// create`), the second `if` (`// list`), but not other two `ifs`?

That's my understanding, that if my `checks` permissions contain only `create` and `list`, your code should _not_ try to read secret and should _not_ try to delete it, but it currently will.

Am I misunderstanding the purpose of that function maybe?

**Comment by saipranav** [comment]
Yup I am dumb 😞 😄 

I understand your points and there are huge holes in the logic.
That function was meant to be designed to have intersection checks too but it does not work as expected and allows the other two if conditions to be true.

I am working on changing this function to be less complex and easier to understand even by a dumb person ( future me ). Also, certain places where this function is called from. I will open a PR and send it for both of you to review.

Thank you so much for contributing ❤️ 
and patiently making me understand the flaws

**Pull request closed without merging**
