### PR TITLE
Add approle support

### PR DESCRIPTION
**Pull request by cyrinux**
Hi,

This add the possibility to use an approle as login, and so a policy with less privileges.
https://www.vaultproject.io/docs/auth/approle

I added a `dest_v3.json` example.
And here an example of vault policy for the origin.

```
path "auth/token/lookup-self" {
  capabilities = ["read"]
}
path "kv/*" {
  capabilities = ["list", "read"]
}
path "kv/data/vsyncChecks" {
  capabilities = ["list", "read", "create", "update", "delete"]
}
path "kv/data/vsyncChecks/*" {
  capabilities = ["list", "read", "create", "update", "delete"]
}
path "kv/metadata/vsyncChecks" {
  capabilities = ["list", "read", "create", "update", "delete"]
}
path "kv/metadata/vsyncChecks/*" {
  capabilities = ["list", "read", "create", "update", "delete"]
}
path "sys/mounts" {
  capabilities = ["list", "read"]
}
path "sys/mounts/*" {
  capabilities = ["list", "read"]
}
``` 

I would like next try to give some improvement in `check.go` and `origin.go` in another PR to be able to give no right permissions at all on the origin.

Regards,

### CODE REVIEW

**Comment by cyrinux** [comment]
Hi @saipranav , friendly ping, any chance you take a look on this PR soon? ;-)

**Comment by saipranav** [comment]
I already looked at this PR and I love this feature. Thanks for the PR.
I would like to update few parts of the code and test it.
I will merge this by 26 March Friday

So sorry for the delays, I wish I can get some solid time to spend on this. I am trying/negotiating to get some office time to be spent here. 


Thanks @cyrinux

**Comment by cyrinux** [comment]
Happy to read you @saipranav , thanks for your reply and ETA. ;)
I wish you negociation will success :-) !
I will retry to do another PR and if I'm stuck I will tell you.

Thanks @saipranav , we keep in touch so 👍🏻

**Comment by saipranav** [comment]
@cyrinux 
I refactored your code and tested I am willing to approve this pull request after your review. I will create a new patch release after approval.

Basically
* added "approle" json object in config and moved "role_id", "secret_id" inside
* new "path" inside approle object for specifying a different path other than default "approle"
* removed unwanted code that does raw request with json serializing for approle login, instead used existing vault API 
* added token renewal to both origin and destination so tokens can live longer if they have a chance
* updated docs

Sorry for the delay and Thanks for understanding the code and contributing ❤️

**Comment by cyrinux** [comment]
Thanks a lot @saipranav, I will try this quickly. I quickly read and all seems to make sense 😃 ❤️ 

In case you want to handle this in the same PR if this make sense for you, while you got time for this project. 
* It would be great to be able to do only ReadOnly checks on the "source" like this the approle can give NO write permissions at all in the approle policies. I started to implement this but I was a little stuck with the logic and how to implement this.
I understand that actually basically try write something then check if we can read. We need to find good way to do such test on a source where we can Read only. 
Tell me what you think about this and you well understand the point ;)

**Comment by saipranav** [comment]
For read-only checks, yup it can be improved and I can understand why it can be valid scenario in wild world.

I wanted to implement the same and ended up with https://github.com/ExpediaGroup/vsync/blob/master/vault/check.go#L142 where you can specify what to check but halfway through figured it is not easy to untangle each check, so implemented the way its right now.

---
For today, you can give a policy that has write access just for `vsyncChecks` folder in kv if that's possible, thereby using same read only for all secrets in kv except vsyncChecks.

**Comment by saipranav** [comment]
I don't want to add those features to the same PR. Let's ship this one

**Comment by cyrinux** [comment]
> For read-only checks, yup it can be improved and I can understand why it can be valid scenario in wild world.
> 
> I wanted to implement the same and ended up with https://github.com/ExpediaGroup/vsync/blob/master/vault/check.go#L142 where you can specify what to check but halfway through figured it is not easy to untangle each check, so implemented the way its right now.
> 
> For today, you can give a policy that has write access just for `vsyncChecks` folder in kv if that's possible, thereby using same read only for all secrets in kv except vsyncChecks.
> 
> I see you already have such a policy in this PR, so that should work fine right?

Yes I confirm you with the policies like this Its Ok ;)
I was able to check your last commit only on the origin part - and its OK, I got a problem on my lab destination but in theory this should be good.

**Comment by saipranav** [comment]
Tested with origin and destination. Squash merging now

**Pull request merged**
